export const FETCH_LISTPOSTS = 'FETCH_LISTPOSTS';
export const FETCH_LISTPOSTS_SUCCESS = 'FETCH_LISTPOSTS_SUCCESS';
export const FETCH_LISTPOSTS_FAIL = 'FETCH_LISTPOSTS_FAIL';

export const DELETE_LISTPOSTS = 'DELETE_LISTPOSTS';

export const ADD_LISTPOSTS = 'ADD_LISTPOSTS';

export const EDIT_LISTPOSTS = 'EDIT_LISTPOSTS';
